### ISSUE TITLE
[BUG] ESM No matching export for import "MultiValueProps"

### ISSUE THREAD

**Issue by baileydoestech** [csandman/chakra-react-select#38]
**Describe the bug**
When upgrading to v3 we are seeing the following build error for ESM (using ViteJS as a build runner):

node_modules/chakra-react-select/dist/esm/types.js:2:9: error: No matching export in "node_modules/react-select/dist/react-select.esm.js" for import "MultiValueProps"

**Additional context**
If we remove/comment out the line `import { MultiValueProps } from "react-select";` in `dist/ems/types.js` everything works as expected

**Comment by csandman** [comment]
I believe this issue was caused by a type conflict between two types declared in the same file, which was causing one of them to be exported as a normal JS object instead of a type.  I restructured the way the types are imported which revealed this conflict and moved one of the offending types to a new location.

Please give [`3.0.2`](https://github.com/csandman/chakra-react-select/releases/tag/v3.0.2) a try and let me know if the issue is fixed!
